---

- name: Install the Packages for my personal flavor of Debian.
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - vim
    - htop
    - sudo
    - gnupg2
    - python3-pip
    - zlib1g-dev
    - uuid-dev
    - libmnl-dev
    - gcc
    - make
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - pkg-config
    - lm-sensors
    - dstat
    - sysstat
    - slurm
    - mtr
    - atop
    - multitail
    - glances
    - ncdu
    - guake=0.8.7-1
    - keepass2
    - unzip
    - rar
    - wireshark
    - terminator
    - comix
